hon_deploy:
  stage: build
  environment:
    name: EC2
    url: http://ec2-54-150-120-136.ap-northeast-1.compute.amazonaws.com/status/
  only:
    refs:
    - master
  image: kroniak/ssh-client
  script:
    - echo "これはmasterのときだけ！"
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - cat "$SSH_PRIVATE_KEY_STAGING" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh ec2-user@ec2-54-150-120-136.ap-northeast-1.compute.amazonaws.com sh /home/ec2-user/auto.sh

dev_deploy:
  stage: build
  environment:
    name: EC2_dev
    url: http://ec2-54-150-120-136.ap-northeast-1.compute.amazonaws.com:8080/status/
  except:
    refs:
    - master
  image: kroniak/ssh-client
  script:
    - echo "これはbranchのときだけ！"
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - cat "$SSH_PRIVATE_KEY_STAGING" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh ec2-user@ec2-54-150-120-136.ap-northeast-1.compute.amazonaws.com sh dev_auto.sh $CI_COMMIT_REF_NAME

dev_test:
  stage: test
  environment:
    name: EC2_dev
    url: http://ec2-54-150-120-136.ap-northeast-1.compute.amazonaws.com:8080/status/
  except:
    refs:
    - master
  image: django
  script:
    - ls -lR
    - echo "$CI_COMMIT_REF_NAME"
