# Generated by Django 3.0.3 on 2020-08-18 14:11

from django.db import migrations, models
from django.utils import timezone

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名前')),
                ('place', models.CharField(choices=[('HOME', '在宅'), ('MEJIRO', '目白台'), ('OOTE', '大手町'), ('DAYOFF', '休暇')], default='目白台', max_length=10, verbose_name='勤務場所')),
                ('status', models.CharField(choices=[('WORK', '勤務中'), ('LEAVE', '離席中'), ('LUNCH', '食事中')], default='勤務中', max_length=10, verbose_name='勤務ステータス')),
                ('last_update_time', models.DateTimeField(default=timezone.now)),
            ],
        ),
    ]

