# Generated by Django 3.0.3 on 2020-08-18 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Worker',
            new_name='Member',
        ),
    ]
